### ISSUE TITLE
Renaming fap snippet to faa

### ISSUE THREAD

**Issue by SparoHawk** [vinliao/fast-arrow#1]
This is just a suggestion. Maybe you could rename **f**ast **a**rrow **p**arams (fap) to **f**ast **a**rrow **a**rguments (faa).

Alternatively you could just opt to use one of the other letters of `params` (_parameters_), and have like: `far` for example.

I could understand it conflicting with `fa` already. Just thought about sharing this idea.

**Comment by vinliao** [comment]
Yeah, I also feel like typing the `fap` keyword while writing code seems a little bit odd, it's an unnecessary distraction. Thanks for the suggestion.

**Comment by vinliao** [comment]
Changed, closing this issue. Thanks for the suggestion @SparoHawk !
