### ISSUE TITLE
Suggestion for args

### ISSUE THREAD

**Issue by hosein2398** [vinliao/fast-arrow#5]
Hey,
I don't if it's technically possible but it would be nice to also define args like:
```
fa.res.rej
```
which results in;
```
(res, rej) => {

}
```
Or the syntax could be:
```
fa.res,rej
```
It would be kinda Emmet for JS :smile:

**Comment by alii2212** [comment]
سلام حسین اقا من این مقاله خوندم 
[https://github.com/hosein2398/node-telegram-bot-api-tutorial](url)

اقا حسین من فقط می تونم در یک مکان کد بنویسم و نمی تونم در اون 
npm install --save node-telegram-bot-api
رو نصب کنم 
سایت زیر 
[http://www.tsetmc.com/Loader.aspx?ParTree=15131F](url)    بالا ی سایت رو قسمت فیلتر کلیک کنید

من فقط اونجا می تونم کدم رو بنویسم حالا می خوام من پیامی رو که به ربات میدم بیاد ریترن کنه return 
و من از اون پیام در ادامه کدم استفاده کنم 
به طور مثال من پیام می دم به ربات

فملی

بیاد فملی رو استرینگ کنه و داخل متغیر قرار بده بعد من از اون متغیر استفاده کنم  

من کد زیر رو نوشتم 

`const TelegramBot = require('node-telegram-bot-api');


const token = '1364017958:AAE8FNHkSdDozXDvqMHM56albRB1pxHAdXA';

// Create a bot that uses 'polling' to fetch new updates

const bot = new TelegramBot(token, {polling: true});


// Listen for any kind of message. There are different kinds of
// messages.
bot.on('message', (msg) => {
  const chatId = msg.chat.id;

  console.log(msg.text);
  // send a message to the chat acknowledging receipt of their message
  
  var text = msg.text;
  
  if(  text.includes((l18))  ){
	return text;
	;
    bot.sendPhoto(chatId,imgUrl);
  }else{
    bot.sendMessage(chatId, 'Received your message:'+text);
  }
});`


ولی نمی دونم بدون نصب  
npm install --save node-telegram-bot-api

چطور اصلاحش کنم 
خیلی ممنون می شوم کمکم کنید

**Comment by alii2212** [comment]
فکر کنم بتونم از 
https://lage.us/Javascript-File-Get-Contents.html  
استفاده کنم

**Comment by vinliao** [comment]
Hey @hosein2398, sorry for the late reply. For some reason, I didn't get the notification from github.

This extension is currently on maintenance mode. No features will be added to it, at least in the near future.
